# Generated by Django 3.1.3 on 2024-10-02 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('government_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('debt_amount', models.IntegerField()),
                ('debt_due_date', models.DateField()),
                ('debt_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
