# Generated by Django 3.1.3 on 2024-10-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('governmentId', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('debtAmount', models.PositiveIntegerField()),
                ('debtDueDate', models.DateField()),
                ('debtId', models.UUIDField(unique=True)),
                ('ticketDate', models.DateTimeField(blank=True, null=True)),
                ('emailDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
