# Generated by Django 3.1.3 on 2024-09-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='emailDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='ticketDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
